### ISSUE TITLE
DST does not build on RHEL6 Linux

### ISSUE THREAD

**Issue by JeremyMcCormick** [omar-moreno/hps-dst#12]
The DST Maker does not build on RHEL6 64 bit which is the standard Linux configuration used at SLAC.

[1102 $] make
[  3%] Building CXX object src/hps_event/CMakeFiles/EcalHit.dir/EcalHit.cxx.o
cc1plus: error: unrecognized command line option "-std=c++11"
make[2]: *** [src/hps_event/CMakeFiles/EcalHit.dir/EcalHit.cxx.o] Error 1
make[1]: *** [src/hps_event/CMakeFiles/EcalHit.dir/all] Error 2
make: *** [all] Error 2

CMake configuration looks fine....

[1103 $] cmake ..
-- Check for ROOT_CONFIG_EXECUTABLE: /u1/apps/root/v5-34-18/root/bin/root-config
-- Check for ROOT (5.34.18)
-- Check for ROOT_EXECUTABLE: /u1/apps/root/v5-34-18/root/bin/root
-- Check for ROOT_CINT_EXECUTABLE: /u1/apps/root/v5-34-18/root/bin/rootcint
-- Check for ROOT_LIBRARIES: Core;Cint;RIO;Net;Hist;Graf;Graf3d;Gpad;Tree;Rint;Postscript;Matrix;Physics;MathCore;Thread
-- Check for ROOT_CORE_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libCore.so -- ok
-- Check for ROOT_CINT_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libCint.so -- ok
-- Check for ROOT_RIO_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libRIO.so -- ok
-- Check for ROOT_NET_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libNet.so -- ok
-- Check for ROOT_HIST_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libHist.so -- ok
-- Check for ROOT_GRAF_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libGraf.so -- ok
-- Check for ROOT_GRAF3D_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libGraf3d.so -- ok
-- Check for ROOT_GPAD_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libGpad.so -- ok
-- Check for ROOT_TREE_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libTree.so -- ok
-- Check for ROOT_RINT_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libRint.so -- ok
-- Check for ROOT_POSTSCRIPT_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libPostscript.so -- ok
-- Check for ROOT_MATRIX_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libMatrix.so -- ok
-- Check for ROOT_PHYSICS_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libPhysics.so -- ok
-- Check for ROOT_MATHCORE_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libMathCore.so -- ok
-- Check for ROOT_THREAD_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libThread.so -- ok
-- Check for libdl.so: /usr/lib64/libdl.so
-- LCIO: /u1/sw/root_dst_maker/lcio-trunk/lib/liblcio.so
-- Check for GBL: it works
-- Generating the HpsEvent ROOT dictionary
-- HpsEvent ROOT dictionary has been generated
-- Check for ROOT_CONFIG_EXECUTABLE: /u1/apps/root/v5-34-18/root/bin/root-config
-- Check for ROOT (5.34.18)
-- Check for ROOT_EXECUTABLE: /u1/apps/root/v5-34-18/root/bin/root
-- Check for ROOT_CINT_EXECUTABLE: /u1/apps/root/v5-34-18/root/bin/rootcint
-- Check for ROOT_LIBRARIES: Core;Cint;RIO;Net;Hist;Graf;Graf3d;Gpad;Tree;Rint;Postscript;Matrix;Physics;MathCore;Thread
-- Check for ROOT_CORE_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libCore.so -- ok
-- Check for ROOT_CINT_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libCint.so -- ok
-- Check for ROOT_RIO_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libRIO.so -- ok
-- Check for ROOT_NET_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libNet.so -- ok
-- Check for ROOT_HIST_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libHist.so -- ok
-- Check for ROOT_GRAF_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libGraf.so -- ok
-- Check for ROOT_GRAF3D_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libGraf3d.so -- ok
-- Check for ROOT_GPAD_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libGpad.so -- ok
-- Check for ROOT_TREE_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libTree.so -- ok
-- Check for ROOT_RINT_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libRint.so -- ok
-- Check for ROOT_POSTSCRIPT_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libPostscript.so -- ok
-- Check for ROOT_MATRIX_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libMatrix.so -- ok
-- Check for ROOT_PHYSICS_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libPhysics.so -- ok
-- Check for ROOT_MATHCORE_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libMathCore.so -- ok
-- Check for ROOT_THREAD_LIBRARY: /u1/apps/root/v5-34-18/root/lib/libThread.so -- ok
-- Check for libdl.so: /usr/lib64/libdl.so
-- Found source: /u1/sw/root_dst_maker/hps-dst/examples/analysis_lcio_example.cxx
-- Source name: analysis_lcio_example
-- Configuring done
-- Generating done
-- Build files have been written to: /u1/sw/root_dst_maker/hps-dst/build

This is the local environment information.

[1002 $] cat /etc/redhat-release
Red Hat Enterprise Linux Workstation release 6.4 (Santiago)

[1003 $] uname -a
Linux ppa-jeremym-l 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Mar 10 17:01:00 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

[1001 $] gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC)

To test/reproduce this you can try building on an rhel6-64 machine.  (I was actually using my local Linux environment but it should be the same.)

**Comment by JeremyMcCormick** [comment]
By the way, a similar gcc version is also used by default on the JLAB systems...

[jeremym@ifarm1101:~ Mon Jun 01 21:32:45]
[1000 $] gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-languages=c,c++,objc,obj-c++,java,fortran,ada --enable-java-awt=gtk --disable-dssi --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-1.5.0.0/jre --enable-libgcj-multifile --enable-java-maintainer-mode --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --disable-libjava-multilib --with-ppl --with-cloog --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.4.6 20110731 (Red Hat 4.4.6-3) (GCC)

So it won't build there either without using a non-default compiler.

**Comment by omar-moreno** [comment]
The DST package uses c++ 11 features so it requires a gcc version > 4.8.  This will need to be installed at SLAC and JLab for it to properly work.  This isn't a problem involving any code.

**Comment by JeremyMcCormick** [comment]
Please do not close this.  It is a major problem because the main Unix work environments for HPS are the shared Linux systems at SLAC and JLAB.  Many collaborators are using only these Linux systems for their work.  So you should make sure either to stay compatible with these environments (e.g. not use C++11 features which I doubt are even necessary) OR you need to provide detailed instructions on how to build the project using an alternate, more up to date compiler chain in these environments.  Most people just trying to run the DST Maker will have no idea how to do this.

**Comment by mholtrop** [comment]
Jeremy, it is 2015. Using C++11 features isn’t any more unreasonable than requiring Java 7.

At JLab, just put  /apps/gcc/4.8.2/bin/ on your path to use g++ 4.8.2. I don’t know about SLAC machines, but it really isn’t too difficult to install 4.8 or later. GCC is now at 5.1, so it’s not even a very fresh release.

**Comment by JeremyMcCormick** [comment]
Leave this open until we actually document how to build this software on the systems where most people will be using it.  Thanks.

**Comment by JeremyMcCormick** [comment]
Maurik, the point is not that this module should have its C++11 features removed.  My suggested resolution is fully documenting how to use an alternate compiler on the Confluence page, so we don't have everyone who wants to install and use it wasting their time solving the same configuration issues on an individual basis.

**Comment by JeremyMcCormick** [comment]
Also, you may want to add to CMakeLists.txt an explicit check for C++11 and fail the build immediately if it is not found.

Some options for doing so found here....

http://stackoverflow.com/questions/10984442/how-to-detect-c11-support-of-a-compiler-with-cmake

**Comment by omar-moreno** [comment]
Jeremy, I understand your point as to wanting to document the installation of an alternate compiler such as gcc 4.8, as it can be difficult.  That said, since you have much more experience doing this, I'm going to assign this task to you.  Please provide a guide outlining the installation of gcc 4.8 (or greater) on both Linux and Mac. Once you have documented this, we can link it to the DST confluence page.  Thanks.

**Comment by JeremyMcCormick** [comment]
Okay, that works for me.

**Comment by JeremyMcCormick** [comment]
I'd consider this sufficiently dealt with as the build instructions now include details about using an up to date compiler at JLAB and SLAC.

https://confluence.slac.stanford.edu/display/hpsg/Installing+the+DST+Tools

You may want to incorporate these changes into the project's README.  At the very least you should clearly state that GCC 4.8+ is required for supporting the C++11 features.
