### ISSUE TITLE
Make the hps-dst package compatible with Mac OS

### ISSUE THREAD

**Issue by omar-moreno** [omar-moreno/hps-dst#16]

**Comment by perhansson** [comment]
Machine

onsdag 5 augusti 2015 skrev Omar Moreno <notifications@github.com>:

**Comment by omar-moreno** [comment]
Matt and Maurik are reporting the following error: 

[ 42%] Building CXX object src/hps_event/CMakeFiles/HpsEvent.dir/HpsEvent.cxx.o
[ 44%] Linking CXX shared library ../../lib/libHpsEvent.dylib
Undefined symbols for architecture x86_64:
  "TObject::SavePrimitive(std::basic_ostream<char, std::char_traits<char> >&, char const*)", referenced from:
      vtable for HpsEvent in HpsEvent.cxx.o
  "HpsEvent::ShowMembers(TMemberInspector&)", referenced from:
      vtable for HpsEvent in HpsEvent.cxx.o
  "HpsEvent::Class()", referenced from:
      HpsEvent::IsA() const in HpsEvent.cxx.o
  "HpsEvent::Streamer(TBuffer&)", referenced from:
      vtable for HpsEvent in HpsEvent.cxx.o
  "ROOTDict::GenerateInitInstance(HpsEvent const*)", referenced from:
      __static_initialization_and_destruction_0(int, int) in HpsEvent.cxx.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libHpsEvent.dylib] Error 1
make[1]: *** [src/hps_event/CMakeFiles/HpsEvent.dir/all] Error 2
make: *** [all] Error 2

**Comment by perhansson** [comment]
Haven't tried in a while. Want me to? Could try updating tonight if you
need another system...

onsdag 5 augusti 2015 skrev Omar Moreno <notifications@github.com>:

**Comment by omar-moreno** [comment]
As @mholtrop  reported, the issue seems to be related to how `rootcit` is executed in ROOT 6 as compared to ROOT 5.   

> Seems the issue is with ROOT. I can run the Issue16 branch on Linux or Mac using ROOT 6, which I use as default. The ROOT team seems to have changed the way rootcint behaves and what parameters it will or will not accept. The v5 rootcint does not accept -I, the v6 requires it.
 
The solution is to add a check to the CMakeLists that changes the `rootcint` command depending on whether ROOT 5 or 6 is detected.  I believe I have a solution, so I will install ROOT 6 locally and test it.

**Comment by omar-moreno** [comment]
@JeremyMcCormick committed changes (found here 330c742a528ff13118624dff7073b47ac693d3db) to the CMakeLists.txt file that fixed the error reported by @bloodyyugo and @mholtrop when trying to link the HpsEvent dictionary. 

The above fix works assuming that the user is linking against the ROOT 5 libraries.  Allowing a user to link against the ROOT 6 libraries required an additional change to the CMakeLists.txt file.  The change as committed by @mholtrop can be viewed here 4cf607c9464a0c692c15bd059394767a76fb251f.

This issue is now resolved and will be closed.
